### ISSUE TITLE
Pipeline aborted 

### ISSUE THREAD

**Issue by ssriera** [pagefront/ember-pagefront#21]
I'm not sure if I've found a bug with the plugin but I've been able to `ember deploy production` from my local machine successfully but the build fails on CircleCi.

```
ubuntu@box4587:~/dashboard$ ember deploy production --verbose
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
    at Object.<anonymous> (/home/ubuntu/dashboard/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:11:23)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
    at Object.<anonymous> (/home/ubuntu/dashboard/node_modules/ember-cli-deploy/lib/tasks/deploy.js:6:23)
Registering hook -> configure[build]
Registering hook -> build[build]
Registering hook -> configure[display-revisions]
Registering hook -> configure[gzip]
Registering hook -> willUpload[gzip]
Registering hook -> configure[manifest]
Registering hook -> willUpload[manifest]
Registering hook -> configure[pagefront]
Registering hook -> willDeploy[pagefront]
Registering hook -> upload[pagefront]
Registering hook -> configure[revision-data]
Registering hook -> prepare[revision-data]
Executing pipeline
|
+- configure
|  |
|  +- build
|    - validating config
|    - Missing config: `environment`, using default: `production`
|    - Missing config: `outputPath`, using default: `tmp/deploy-dist`
|    - config ok
|  |
|  +- display-revisions
|    - validating config
|    - Missing config: `amount`, using default: `[Function]`
|    - config ok
|  |
|  +- gzip
|    - validating config
|    - Missing config: `filePattern`, using default: `**/!(*.html)`
|    - Missing config: `zopfli`, using default: `false`
|    - Missing config: `keep`, using default: `false`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - config ok
|  |
|  +- manifest
|    - validating config
|    - Missing config: `filePattern`, using default: `**/!(*.html)`
|    - Missing config: `manifestPath`, using default: `manifest.txt`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - config ok
|  |
|  +- pagefront
|    - validating config
|    - config ok
|  |
|  +- revision-data
|    - validating config
|    - Missing config: `type`, using default: `file-hash`
|    - Missing config: `filePattern`, using default: `index.html`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - Missing config: `versionFile`, using default: `package.json`
|    - config ok
|
+- setup
|
+- willDeploy
|  |
|  +- pagefront
|    - Preparing for deploy...
|
+- willBuild
|
+- build
|  |
|  +- build
|    - building app to `tmp/deploy-dist` using buildEnv `production`...
cleaning up
cleaning up...
|    - ✔  assets/dashboard-a6f32008fbe04a2c5d68ec2e0c9832fd.js
|    - ✔  assets/dashboard-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/vendor-e675cb22f0a6494e18de01548a4e6325.js
|    - ✔  crossdomain.xml
|    - ✔  images/FS-logo-blue-mark-7b41c0a79922ea8aa04a38f72a3f122f.png
|    - ✔  index.html
|    - ✔  robots.txt
|    - build ok
|
+- didBuild
|
+- willPrepare
|
+- prepare
|  |
|  +- revision-data
|    - creating revision data using `file-hash`
|    - generated revision data for revision: `e5a764db59402dbe711feb468fba1ad3`
|
+- didPrepare
|
+- willUpload
|  |
|  +- gzip
|    - gzipping `**/!(*.html)`
|    - ✔  assets/dashboard-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/dashboard-a6f32008fbe04a2c5d68ec2e0c9832fd.js
|    - ✔  crossdomain.xml
|    - ✔  robots.txt
|    - ✔  images/FS-logo-blue-mark-7b41c0a79922ea8aa04a38f72a3f122f.png
|    - ✔  assets/vendor-e675cb22f0a6494e18de01548a4e6325.js
|    - gzipped 7 files ok
|  |
|  +- manifest
|    - generating manifest at `manifest.txt`
|    - generated manifest including 7 files ok
|
+- upload
|  |
|  +- pagefront
|
+- didFail
[object Object]
undefined|
Pipeline aborted
```

Also, CircleCi has the environment PAGEFRONT_KEY variable. 
The build fails even with the `ember-cli-deploy-pagefront` plugin.

**Comment by ssriera** [comment]
The issue was I had the wrong API key for PAGEFRONT_KEY.
